#!/usr/bin/env php
<?php

$dbTest = false;
$className = '';

foreach ($argv as $i => $arg) {
    if ($i > 0) {
        if ($arg[0] == '-') {
            $param = substr($arg, 1);
            if ($param == 'db') {
                $dbTest = true;
            }
        } else {
            $className = $arg;
        }
    }
}

if (empty($className)) {
    echo "Usage: mktest [-db] classname" . PHP_EOL;
} else {
    $pathToTest = 'test/' . $className . 'Test.php';
    $chunks = explode('/', $className);
    $simpleClassName = array_pop($chunks);
    $className = str_replace('/', '\\', $className);

    $php = "<?php\n\n" .
        "use PHPUnit\\Framework\\TestCase;\n\n" .
        "use Framewub\\{$className};\n";

    if (!$dbTest) {
        $php .= "\nclass {$simpleClassName}Test extends TestCase\n{\n" .
            "    public function testFunction()\n    {\n\n    }\n}\n";
    } else {
        $php .= "use Framewub\\Db\\MySQL;\n\n" .
            "class {$simpleClassName} extends \PHPUnit_Extensions_Database_TestCase\n{\n" .
            "    private $sharedPdo;\n    private $db;\n\n" .
            "    public function __construct()\n    {\n" .
            "        \$this->db = new MySQL([ 'dbname' => 'framewub_test' ], 'framewub', 'fr4m3wu8');\n" .
            "        \$this->sharedPdo = \$this->db->getPdo();\n" .
            "    }\n" .
            "    /**\n     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection\n     */" .
            "    public function getConnection()\n    {\n        return \$this->createDefaultDBConnection(\$this->sharedPdo, 'framewub_test');\n    }\n\n" .
            "    /**\n     * @return PHPUnit_Extensions_Database_DataSet_IDataSet\n     */\n" .
            "    public function getDataSet()\n    {\n        return $this->createFlatXMLDataSet(dirname(dirname(__DIR__)).'/data/test-seed.xml');\n    }\n" .
            "}\n";
    }

    file_put_contents($pathToTest, $php);

}